displayName=Farming Profit
author=MKuijpers
description=Calculates the profit of a farm run by tracking harvested crops
tags=farm,farming,runs,run,profit,money,herb,allotment
plugins=com.farmingprofit.FarmingProfitPlugin
version=
build=standard
